### PR TITLE
Maven build & release setup

### PR DESCRIPTION
**Pull request by btilford**
I added a maven pom setup to build the project and with configurations to release to sonatype repository. 

See [Sonatype OSS Maven Repository User Guide](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide) for instructions on getting a staging repository if your interested in doing that.

### CODE REVIEW

**Comment by brian428** [comment]
I believe Ben and Chris are at a customer site this week so it may be a bit longer before they have a chance to give this a more thorough look.

**Comment by cliffmeyers** [comment]
If we add support for artifact publishing using our existing Ant-based builds and the Maven Ant Tasks library, will that meet your needs?

**Comment by btilford** [comment]
That would probably work, would you plan on deploying to a public maven
repo?

sent from mobile
On Jul 14, 2011 11:22 AM, "cliffmeyers" <
reply@reply.github.com>
wrote:

**Comment by cliffmeyers** [comment]
Yes, we are in the process of getting set up over on Maven central.  We should have this set up within the next couple weeks.

**Comment by btilford** [comment]
Great I'll be looking for it.

**Pull request closed without merging**
