### PR TITLE
Complete manifest.xml file and Fix to crash error in verifyTag()

### PR DESCRIPTION
**Pull request by josebarragan**
The manifest.xml file describe wich classes will be export into the library package, even all classes referenced by some one that has been describe in it yet, will be exported too, right?
We use AbstractController on our architecture, and some interfaces too, and with the manifest.xml has you provoded, this class, and others has not been include into the library.
I can't review all your code for evaluates wich classes must be include into manifest.xml to obtained an complete library, for that, I've use the flexmojos manifest generator to create it.
Please, think about my explanation, and sorry for my poor english.

### CODE REVIEW

**Comment by josebarragan** [comment]
For the fix to crashing error in verifyTag(), this is my explanation:

In theory, your 'if' evaluate metadataTag.properties for a null value, but (I don'
t understand for what), even being 'metadataTag.properties == null', as3 continue trying ev
alutates the next clause: 'metadataTag.properties.length < hostMethod.requiredParameterCo
unt' and this make a system crash with a NullPointerException.

I made a simple change for evaluate only the attribute properties, and only if properties is distinct to null, cascade the logical 'and'  with another subrogate 'if'

I hope, that now you can evaluate this pull request without pain ;)

**Comment by bclinkinbeard** [comment]
Regarding the manifest, including classes in the SWC is not the purpose and we have never listed all of the classes in the manifest. See http://livedocs.adobe.com/flex/3/html/help.html?content=compilers_31.html for a basic discussion of the subject.

**Comment by josebarragan** [comment]
Ok, finally everything has sense

This is the correct sentence, the old changes at this point not has sense.

The problem was, you've extra '( )' in your OR clause,  creating thr
ee clauses as this :  

if( [clause != null] && [clause < count] || [clause > count] )

allways will evaluates third clause and crash causing NullPointerException when 'properties == null'.

The fix, set the sentence in two clauses as this: 

if( [clause !=null] && [ [clause < count] || [clause > count] ] )

Regards Ben

**Comment by josebarragan** [comment]
In relation to manifest.xml, you're right, I had an error in my pom.xml. Therefore, indeed, it's not necessary to include more classes of those than you had including already.

**Comment by josebarragan** [comment]
We used an instance of SharedObjectBean like as:

```
<swiz:SharedObjectBean id="rememberComputerSharedObject"
                          name="rememberComputerSharedObject"/>
```

on our LoginBeanProvider, it's an MXML file.

**Comment by josebarragan** [comment]
To optimize the search parent swiz event, I  added an 'stopPropagation', to avoid the next propagation throught display list hierachy for nothing to do.

**Comment by bclinkinbeard** [comment]
You are correct about the parentheses in verifyTag(), that was a mistake. That being said, there should be a separate pull request per feature/fix. One for verifyTag(), one for SharedObjectBean, one for stopPropagation(). I am going to close this and will implement these changes but please remember this in the future.

**Comment by josebarragan** [comment]
Ok, and many thanks. 

I tried to create an separated pull request as you told me, but GitHub indicates me that I only can have one open pull request at time, I don't know how I ca do it.

Regards

**Pull request closed without merging**
